# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://latrmouh.org/
baseurl: /
title: Laïla Atrmouh
author: Laïla Atrmouh
description: Personal blog and resume
avatar: profile.png
email: hi@latrmouh.org
github: leiluspocus # username
twitter: leiluspocus
linkedin: lailatrmouh
stackoverflow: users/1704966/laila   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-47952004-1


# needed for travis-ci build
exclude: [vendor]
